---
- name: "Restart zabbix agent"
  ansible.builtin.service:
    name: "zabbix-agent"
    state: "restarted"

- name: "Restart zabbix agent 2"
  ansible.builtin.service:
    name: "zabbix-agent2"
    state: "restarted"
