---
#
# Default variables for Nginx
#

with_nginx: false
with_nginx_sury: false

nginx_workers: "auto"
nginx_http_config: []
nginx_security_xframeoptions: true
nginx_security_xxssprotection: true
nginx_security_xcontenttypeoptions: true
nginx_fpm_openbasedir_enforced: false
nginx_logfmt_json: false

selfvhost_nginx_enabled: true
phpmyadmin_nginx_enabled: true
phpsyscheck_nginx_enabled: true
