---
#
# Default variables
#

ansible_master: "root@localhost"

admins: []
admins_emails:
  - "root@localhost"
with_admins_accounts: true

locale: "en_US.UTF-8"
timezone_area: "Europe"
timezone_city: "Paris"

with_hosts: false
with_hostsdeny: false
hosts_fqdn: true
hosts_static_lookup: []
ipv6_disabled: false

debian_mirror: "https://deb.debian.org"

apt_keys: []
apt_repositories: []
apt_additional_packages: []
apt_additional_packages_local: []
with_apt_sources: false
with_apt_backports: false
with_base_packages: true

hosts_deny_nfs: false
host_deny_paranoid: false

with_auto_upgrade: false
auto_upgrade_additional_patterns: []
with_logcheck: false
with_rkhunter: false
with_chkrootkit: false

with_logrotate4rsyslog_override: true

with_hideproc: false
hideproc_gid: ""

with_sudo: true

with_dhparam: true

with_ntp: true

with_firewall: false
firewall_debug: false
firewall_interface:
firewall_public:
  - "ssh"
  - "http"
  - "https"
  - "smtp"

with_smartd: false

with_postfix: false
postfix_ssl_fortify: false
with_postfix_slowsmtp: false
with_mail_aliases: false
with_postfix_external_smtp: false
postfix_external_smtp_host_localdomain:
postfix_external_smtp_credentials:
postfix_external_smtp_relays:
postfix_external_sender_rewrites:
dkim_domains: []
dkim_selector: "default"
with_opendkim: false

with_rspamd: false
with_rspamd_upstream: false
rspamd_composites: true
rspamd_actions: true
rspamd_actions_score_reject: 30
rspamd_actions_score_add_header: 6
rspamd_actions_score_greylist: 4
rspamd_actions_score_rewrite_subject: 8
rspamd_multimap: true
rspamd_multimap_prefix: ""
rspamd_external_relay: []
rspamd_rbl_group: true
rspamd_redis_history: true
rspamd_redis_history_nrows: 200
rspamd_surbl_group: true
rspamd_multimap_rules_body_spammy: []
rspamd_multimap_rules_headers_spammy: []
rspamd_multimap_whitelist_sender: []
rspamd_multimap_whitelist_sender_domain: []
rspamd_multimap_blacklist_sender: []
rspamd_multimap_blacklist_sender_domain: []
rspamd_multimap_score_whitelist_envfrom: -9.0
rspamd_multimap_score_whitelist_envfrom_domain: -9.0
rspamd_multimap_score_whitelist_from: -2.2
rspamd_multimap_score_whitelist_from_domain: -2.2
rspamd_multimap_score_blacklist_from: 20.0
rspamd_multimap_score_blacklist_from_domain: 20.0
rspamd_multimap_score_spammy_body: 1.0
rspamd_multimap_score_check_headers: 1.0
rspamd_whitelist: true
rspamd_whitelist_dmarc: []
rspamd_whitelist_spfdkim: []
rspamd_metrics: {}
rspamd_regexp: true
rspamd_milter_headers: true

with_rspamd_web: false
rspamd_web_vhostname: "rspamd.localhost"
rspamd_web_vhostip:
rspamd_web_vhostip6:
rspamd_web_vhostport: 80
rspamd_web_vhostport_ssl: 443
rspamd_web_http3: false
rspamd_web_ssl: false
rspamd_web_http_auth: true
rspamd_web_http_whitelist_ip: []
rspamd_web_http_auth_admin_password: ""

with_ssh: true
ssh_strengthened: true
ssh_ports:
  - 22
ssh_usedns: true
ssh_allowed_users: []
ssh_allowed_groups:
  - "root"
  - "operator"
  - "{% if ansible_facts['lsb']['major_release'] | int >= 12 %}_{% endif %}ssh"

with_dnscache: false

with_docker: false
with_docker_upstream: false

sysfs_disk_settings: false

with_dotfiles: false
dotfiles_repo: "https://git.openics.org/kolter/dotfiles-sys.git"
dotfiles_dest: "/srv/hosting-tools/shell"
dotfiles_lcsshvars: 0

ssl_certs: []
ssl_certs_auto: []
with_geoip: false
geoip_accountid:
geoip_licencekey:
geoip_editionids: []
